spring:
  application:
    name: eureka-naming-server
server:
  port: 8741
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8741/eureka/ # Still needed for clients to find it
    register-with-eureka: false  # Don?t register itself
    fetch-registry: false        # Don?t fetch registry (it?s the source)
  server:
    enable-self-preservation: false